### ISSUE TITLE
null error

### ISSUE THREAD

**Issue by AnnaMag** [geelen/Snap.svg-cjs#4]
snapsvg-cjs is installed in the package.json and called via Snap = require('snapsvg-cjs'), bundle compiles with no problems (webpack of course:)).
var s = Snap("14in","14in") returns null, so does var s = Snap("#svg")
Any ideas?
Would it be possible to see a working example?

**Comment by devsli** [comment]
Hi @AnnaMag! Just found this wonderful repo.
Did you found the solution? Do you have `<... id="svg">` element?
Do you call `Snap("#svg")` after page is loaded?

**Comment by AnnaMag** [comment]
@devsli, I had to put it aside- could not find a workaround and needed to progress, so used alternatives. Will try again in the future.

**Comment by vincent-derks** [comment]
Hi @AnnaMag, did you try calling `Snap` and passing it an existing SVG element? Sounds like it can't find the element you are passing it. If there is no existing element yet, you can call `Snap` and pass it the dimensions you are looking for, so it creates a new element for you. For example `Snap(100,100)`. If you already have an existing SVG, make sure it's loaded in the DOM when you are calling `Snap`.
